-- Generated by HiveQL Generator, please don't modify.
-- https://git.shiyou.kingsoft.com/data/hiveql-generator
-- 创建 OmniSDK 订单创建事实表
CREATE TABLE IF NOT EXISTS dw_omni_sdk.dwd_fact_omni_sdk_order_create_di(
    time_ms string COMMENT '上报的时间',
    service_group string COMMENT '数据源',
    datasource string COMMENT '请求来源',
    game_id string COMMENT '应用 ID',
    msg_version string COMMENT '消息版本',
    sdk_version string COMMENT 'SDK 版本',
    channel string COMMENT '渠道名称',
    device_id string COMMENT '设备 ID',
    account_id string COMMENT 'SDK 用户唯一 ID',
    host string COMMENT '客户端请求 Host',
    os string COMMENT '操作系统类型',
    os_version string COMMENT '操作系统版本',
    vendor string COMMENT '手机品牌',
    device_model string COMMENT '手机型号',
    event_group string COMMENT '数据类型',
    event_name string COMMENT '事件类型',
    another_device_id string COMMENT '另一个设备 ID',
    ip string COMMENT '客户端IP',
    order_id string COMMENT '订单 ID',
    amount string COMMENT '金额',
    notify_url string COMMENT 'URL',
    role_id string COMMENT '角色 ID',
    currency_code string COMMENT '币种',
    ios string COMMENT '是否为ios设备',
    android string COMMENT '是否为android设备',
    desktop string COMMENT '否为桌面设备',
    mobile string COMMENT '是否为手机',
    smarttv string COMMENT '是否为智能电视',
    tablet string COMMENT '是否为平板电脑',
    country string COMMENT '国家/地区代码',
    city string COMMENT '城市名称',
    country_region_name string COMMENT '区域名称',
    latitude string COMMENT '纬度纬度',
    longitude string COMMENT '经度',
    time_zone string COMMENT '时区',
    http_version string COMMENT '请求的 HTTP 版本'
) COMMENT ' OmniSDK 订单创建事实表'
PARTITIONED BY (dt string)
STORED AS ORC;
