-- Generated by HiveQL Generator, please don't modify.
-- https://git.shiyou.kingsoft.com/data/hiveql-generator
-- 创建OmniSDK订单明细事实表
CREATE TABLE IF NOT EXISTS dm_omni_sdk.dwb_fact_omni_sdk_order_detail_di(
    account_id string COMMENT 'SDK 用户唯一 ID',
    order_id string COMMENT '订单 ID',
    create_order_time string COMMENT '创建订单时间',
    complete_order_time string COMMENT '完成订单时间',
    create_order_amount string COMMENT '创建订单金额',
    complete_order_amount string COMMENT '完成订单金额',
    currency_code string COMMENT '币种',
    channel string COMMENT '渠道名称',
    os string COMMENT '操作系统类型',
    os_version string COMMENT '操作系统版本',
    vendor string COMMENT '手机品牌',
    device_model string COMMENT '手机型号',
    service_group string COMMENT '数据源',
    datasource string COMMENT '请求来源',
    game_id string COMMENT '应用 ID',
    msg_version string COMMENT '消息版本',
    sdk_version string COMMENT 'SDK 版本',
    device_id string COMMENT '设备 ID',
    host string COMMENT '客户端请求 Host',
    event_group string COMMENT '数据类型',
    another_device_id string COMMENT '另一个设备 ID',
    ip string COMMENT '客户端IP',
    notify_url string COMMENT 'URL',
    role_id string COMMENT '角色 ID',
    header_os string COMMENT 'header 操作系统类型',
    header_device string COMMENT 'header 操作设备类型',
    country string COMMENT '国家/地区代码',
    city string COMMENT '城市名称',
    country_name string COMMENT '国家名称',
    country_region_name string COMMENT '区域名称',
    latitude string COMMENT '纬度',
    longitude string COMMENT '经度',
    time_zone string COMMENT '时区',
    http_version string COMMENT '请求的 HTTP 版本'
) COMMENT 'OmniSDK订单明细事实表'
PARTITIONED BY (dt string)
STORED AS ORC;
