-- Generated by HiveQL Generator, please don't modify.
-- https://git.shiyou.kingsoft.com/data/hiveql-generator
-- 从OmniSDK 上报事件表 dw_omni_sdk.ods_omni_sdk_event_di 向  OmniSDK 订单创建事实表 dw_omni_sdk.dwd_fact_omni_sdk_order_create_di 提取数据


WITH rs_get_json_object AS(
    SELECT
        ods_omni_sdk_event_di.dt,
        raw_json_view.*,
        properties_view.*
        FROM dw_omni_sdk.ods_omni_sdk_event_di --
        lateral VIEW json_tuple(
        raw_json,
        "#account_id",
        "#datasource",
        "#event_name",
        "#properties",
        "#time_ms"
        ) raw_json_view AS
        account_id,
        datasource,
        event_name,
        properties,
        time_ms
        lateral VIEW json_tuple(
        properties,
        "amount",
        "android",
        "another_device_id",
        "#channel",
        "city",
        "country",
        "country_region_name",
        "currency_code",
        "desktop",
        "#device_id",
        "#device_model",
        "#event_group",
        "game_id",
        "host",
        "http_version",
        "ios",
        "#ip",
        "#latitude",
        "#longitude",
        "mobile",
        "#msg_version",
        "notify_url",
        "order_id",
        "#os",
        "#os_version",
        "#role_id",
        "#sdk_version",
        "#service_group",
        "smarttv",
        "tablet",
        "time_zone",
        "#vendor"
        ) properties_view AS
        amount,
        android,
        another_device_id,
        channel,
        city,
        country,
        country_region_name,
        currency_code,
        desktop,
        device_id,
        device_model,
        event_group,
        game_id,
        host,
        http_version,
        ios,
        ip,
        latitude,
        longitude,
        mobile,
        msg_version,
        notify_url,
        order_id,
        os,
        os_version,
        role_id,
        sdk_version,
        service_group,
        smarttv,
        tablet,
        time_zone,
        vendor
       WHERE dt = :dt
          AND event_name = 'create_order'
),
rs_get_rank AS (
    SELECT *
    FROM (
            SELECT *,
                ROW_NUMBER() OVER(
                    PARTITION BY
                    time_ms,
                    datasource,
                    account_id,
                    event_name
                    ) AS rk
            FROM rs_get_json_object
        ) AS rs_rank
    WHERE rk=1
)

-- 将最终结果放入 OmniSDK 订单创建事实表( dw_omni_sdk.dwd_fact_omni_sdk_order_create_di )中
INSERT OVERWRITE TABLE dw_omni_sdk.dwd_fact_omni_sdk_order_create_di PARTITION (dt = :dt)
SELECT
    time_ms,
    service_group,
    datasource,
    game_id,
    msg_version,
    sdk_version,
    channel,
    device_id,
    account_id,
    host,
    os,
    os_version,
    vendor,
    device_model,
    event_group,
    event_name,
    another_device_id,
    ip,
    order_id,
    amount,
    notify_url,
    role_id,
    currency_code,
    ios,
    android,
    desktop,
    mobile,
    smarttv,
    tablet,
    country,
    city,
    country_region_name,
    latitude,
    longitude,
    time_zone,
    http_version
FROM  rs_get_rank;
